version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql/tmp:/sql_tmp
    restart: always
    environment:
      MYSQL_DATABASE: anime
      MYSQL_USER: admin
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mariadb
      - PMA_USER=admin
      - PMA_PASSWORD=mariadb
    ports:
      - "3001:80"