FROM node:latest
MAINTAINER hirarira

# 環境変数設定
ENV ANIME_DB_USER_NAME=root
ENV ANIME_DB_PASS=mariadb
ENV ANIME_DB_HOST=mariadb
ENV ANIME_SHOBOI_CALENDAR_USERNAME=hirarira617

WORKDIR /server/
