SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `anime` (
  `tid` int(11) NOT NULL,
  `title` text NOT NULL,
  `chName` varchar(50) NOT NULL,
  `url` text NOT NULL,
  `hashTag` varchar(30) NOT NULL,
  `characterURL` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `animeStory` (
  `id` int(11) NOT NULL,
  `TID` int(11) NOT NULL,
  `Count` int(11) NOT NULL,
  `StTime` int(11) NOT NULL,
  `EdTime` int(11) NOT NULL,
  `LastUpdate` int(11) NOT NULL,
  `SubTitle` text NOT NULL COMMENT 'サブタイトル',
  `minogashi` tinyint(4) NOT NULL DEFAULT '0' COMMENT '見逃しフラグ',
  `comment` text NOT NULL COMMENT 'ユーザコメント'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `anime`
  ADD PRIMARY KEY (`tid`);

ALTER TABLE `animeStory`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `animeStory`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=237;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
